---
- name: Add static route to IOS device
  hosts: router1
  gather_facts: no

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Cisco configure rote
      cisco.ios.ios_config:
        lines:
          - show version
